name = "Azgard"
author = "Azgard Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5a45da9a8ec1e1a8369f355d6de537885e10de3398e86c84015c341a284dd5a"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
